name: tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install PAM headers
        run: sudo apt update && sudo apt install -y libpam0g-dev

      - run: go test -count=1 ./...
